# Generated by Django 4.1.6 on 2023-02-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('prijmeni', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=20)),
                ('adresa', models.CharField(max_length=20)),
                ('mesto', models.CharField(max_length=20)),
                ('psc', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=20)),
                ('castka', models.PositiveIntegerField()),
                ('predmet', models.CharField(max_length=20)),
                ('platnost_od', models.DateField()),
                ('platnost_do', models.DateField()),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.pojistenec')),
            ],
        ),
    ]
